name: xue_hua_webview_windows
version: 1.0.1
description: A Flutter plugin that provides a WebView widget on Windows.
repository: https://github.com/Matkurban/xue_hua_webview
homepage: https://github.com/Matkurban/xue_hua_webview
issue_tracker: https://github.com/Matkurban/xue_hua_webview/issues

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

flutter:
  plugin:
    implements: xue_hua_webview
    platforms:
      windows:
        pluginClass: WebviewWindowsPlugin
        dartPluginClass: WindowsWebViewPlatform

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0
  path: ^1.9.1
  xue_hua_webview_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ">=26.3.4 <27.1.1"

topics:
  - webview
  - webview-flutter
  - windows
  - html
  - browser
