name: xue_hua_webview
version: 1.0.1
description: A WebView plugin supporting Android, iOS, macOS, Windows, Linux, and Web, with an API compatible with webview_flutter.
repository: https://github.com/Matkurban/xue_hua_webview
homepage: https://github.com/Matkurban/xue_hua_webview
issue_tracker: https://github.com/Matkurban/xue_hua_webview/issues

platforms:
  android:
  ios:
  macos:
  linux:
  windows:
  web:

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: xue_hua_webview_android
      ios:
        default_package: xue_hua_webview_wkwebview
      macos:
        default_package: xue_hua_webview_wkwebview
      linux:
        default_package: xue_hua_webview_linux
      windows:
        default_package: xue_hua_webview_windows
      web:
        default_package: xue_hua_webview_web

dependencies:
  flutter:
    sdk: flutter
  xue_hua_webview_android: ^1.0.0
  xue_hua_webview_wkwebview: ^1.0.0
  xue_hua_webview_platform_interface: ^1.0.0
  xue_hua_webview_windows: ^1.0.0
  xue_hua_webview_linux: ^1.0.0
  xue_hua_webview_web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - webview
  - webview-flutter
  - html
  - javascript
  - browser
