name: example
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.13.0
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  xue_hua_webview:
    path: ../
  cupertino_icons: ^1.0.9
  material_ui: ^1.4.0
  cupertino_ui: ^1.1.1
  flex_color_scheme: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  xue_hua_webview_platform_interface: ^1.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/file_chooser.html
